name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using the read-only token
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yoscam2  # Your Docker Hub username
          password: ${{ secrets.DOCKER_HUB_READ_ONLY_TOKEN }}  # Read-only token

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Use the current directory as the build context
          push: true  # Push the image to Docker Hub
          tags: yoscam2/metrics-app:latest  # Tag the image with your Docker Hub username